src/commands/cmd_common.js, src/commands/connections/cmd.js, src/commands/idm/cmd.js, src/commands/info/cmd.js, src/commands/journey/cmd.js, src/commands/logging/cmd.js
=> Converted -h, -r, -u, -p, -k, -s options to arguments for all commands.

src/api/TreeApi.js, src/api/utils/ApiUtils.js
=> Fix journey import.

README.md, src/api/AuthApi.js, src/api/utils/DataProtection.js
- updated readme with usage instructions
- the initconnection now create a folder called ./frodo under the user profile and stores the connection rc inside along with the masterkey
- this change will break existing saved connections so you'll need to reinitiate
closes #43 
closes #27
=> updated readme and consolidated settings under one folder

src/api/EmailTemplateApi.js, src/app.js, src/commands/email_templates/cmd.js
Added handling of email template management independent of journeys.
=> implemented independent email template management

README.md, src/commands/logging/cmd.js
Updated readme with better instructions and added build instructions. Build instructions needs review from @vscheuber
=> Updated readme and fixed typo in logs command

src/api/AuthApi.js, src/api/BaseApi.js, src/api/LogApi.js, src/commands/cmd_common.js, src/commands/email_templates/cmd.js, src/commands/idm/cmd.js, src/commands/info/cmd.js, src/commands/journey/cmd.js, src/commands/logging/cmd.js, src/commands/script/cmd.js, src/storage/SessionStorage.js
=> Resolves #50 and #56

src/api/TreeApi.js
=> Resolves #57

.gitignore, src/api/AmServiceApi.js, src/api/ApplicationApi.js, src/api/utils/ExportImportUtils.js, src/app.js, src/commands/application/cmd.js
=> implemented application export and import

src/api/utils/Console.js
=> Fix color of 'info' output in Console.js

src/api/ThemeApi.js, src/api/utils/ExportImportUtils.js, src/app.js, src/commands/theme/cmd.js
=> Implement theme list/export/import commands

src/commands/script/cmd.js
=> Add rename and re-uuid capabilties to script command

src/api/TreeApi.js
=> Import script dependencies first during journey import

.github/workflows/frodo.yml, README.md
=> Update to node18

package-lock.json, package.json, src/api/utils/ExportImportUtils.js, src/cli/script/cmd.js
=> Slugify strings before using them as filenames

src/api/CirclesOfTrustApi.js, src/cli/saml/saml-cot-export.js, src/cli/saml/saml-cot-import.js, src/cli/saml/saml-cot-list.js, src/cli/saml/saml-cot.js, src/cli/saml/saml-import.js, src/ops/CirclesOfTrustOps.js, src/ops/IdpOps.js, src/ops/SamlOps.js
=> Support circles of trust

src/app.js, src/storage/SessionStorage.js
=> Include exportToolVersion in export meta data

src/cli/info/cmd.js
=> fixes #192

package-lock.json, package.json, src/cli/cmd_common.js, src/cli/journey/journey-describe.js, src/cli/journey/journey-export.js, src/cli/journey/journey-import.js, src/ops/JourneyOps.js, src/ops/utils/Console.js, src/ops/utils/OpsUtils.js
Resolves #197 
Resolves #195 
Resolves #194
=> Journey commands enhancements and breaking changes

src/ops/JourneyOps.js
=> Fix journey export format backwards compatibility issue on import

src/api/IdmConfigApi.js, src/api/OrganizationApi.js, src/api/ThemeApi.js, src/cli/idm/cmd.js, src/ops/AdminOps.js, src/ops/IdmOps.js
=> Split idm api and ops layers and fix exportAllRaw bug

src/api/IdmConfigApi.js, src/ops/AdminOps.js, src/ops/IdmOps.js
Resolves #162 
Resolves #210 
Extends #211
=> Fixed error handling

src/cli/logging/logs-tail.js, src/ops/LogOps.js
=> Implement #208

src/ops/JourneyOps.js
=> Detect and remove invalid tree attributes on import

src/api/Saml2Api.js, src/cli/saml/saml-describe.js, src/cli/saml/saml-metadata-export.js, src/cli/saml/saml-metadata.js, src/cli/saml/saml.js, src/ops/SamlOps.js, src/ops/utils/Console.js, src/ops/utils/ExportImportUtils.js
=> saml command enhancements

src/api/AuthApi.js, src/ops/JourneyOps.js
=>  Fixed issue where overriding deployment type would fail to detect the default realm

src/cli/theme/cmd.js
=> Fix theme import -A

src/api/TreeApi.js, src/cli/journey/journey-delete.js, src/cli/journey/journey-describe.js, src/cli/journey/journey.js, src/ops/JourneyOps.js
=> New journey delete command

src/cli/journey/journey-delete.js, src/cli/journey/journey-export.js, src/ops/JourneyOps.js, src/ops/utils/Console.js
Improved journey delete functions and fixed a dependency resolution issue during import.
=> Journey delete and import fixes

test/e2e/journey/baseline/ForgottenUsername.journey.json, test/e2e/journey/baseline/Login.journey.json, test/e2e/journey/baseline/PasswordGrant.journey.json, test/e2e/journey/baseline/ProgressiveProfile.journey.json, test/e2e/journey/baseline/Registration.journey.json, test/e2e/journey/baseline/ResetPassword.journey.json, test/e2e/journey/baseline/UpdatePassword.journey.json, test/e2e/journey/baseline/allAlphaJourneys.journeys.json
=> Baseline OOTB journeys

src/cli/journey/journey-list.e2e.test.js
=> journey list e2e test suite

src/api/ThemeApi.js, src/api/utils/ApiUtils.js
=> Fix theme import issues when using /alpha or /bravo instead of alpha or bravo

package.json, src/cli/journey/journey-delete.e2e.test.js, src/cli/journey/journey-list.e2e.test.js, test/e2e/journey/delete/ForgottenUsername.journey.json, test/e2e/journey/delete/Login.journey.json, test/e2e/journey/delete/PasswordGrant.journey.json, test/e2e/journey/delete/ProgressiveProfile.journey.json, test/e2e/journey/delete/Registration.journey.json, test/e2e/journey/delete/ResetPassword.journey.json, test/e2e/journey/delete/UpdatePassword.journey.json, test/e2e/journey/delete/deleteMe.journey.json, test/e2e/journey/list/Disabled.journey.json, test/e2e/journey/list/ForgottenUsername.journey.json, test/e2e/journey/list/Login.journey.json, test/e2e/journey/list/PasswordGrant.journey.json, test/e2e/journey/list/ProgressiveProfile.journey.json, test/e2e/journey/list/Registration.journey.json, test/e2e/journey/list/ResetPassword.journey.json, test/e2e/journey/list/UpdatePassword.journey.json
Resolves #231 
Resolves #230 
Resolves #241
=> journey list/delete e2e tests 

src/api/ThemeApi.js, src/cli/theme/theme-delete.e2e.test.js, src/cli/theme/theme-list.e2e.test.js, test/e2e/theme/baseline/Contrast.theme.json, test/e2e/theme/baseline/Highlander.theme.json, test/e2e/theme/baseline/Robroy.theme.json, test/e2e/theme/baseline/Starter-Theme.theme.json, test/e2e/theme/baseline/Zardoz.theme.json, test/e2e/theme/import/Contrast.theme.json, test/e2e/theme/import/Highlander.theme.json, test/e2e/theme/import/Robroy.theme.json, test/e2e/theme/import/Starter-Theme.theme.json, test/e2e/theme/import/Zardoz.default.theme.json
Resolves #248 
Resolves #247 
Resolves #246
=> Theme list and delete e2e tests

.github/workflows/frodo.yml, dist/package-lock.json, dist/package.json, package-lock.json, package.json, src/ops/utils/Console.js
=> Fix binary builds and implement basic smoke test

.github/workflows/frodo.yml
=> Switched windows binary release runner from linux to windows
